# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-setuppy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # `install-python` action no longer supports 2.7 (as of 22-05-2024), so using docker images
      matrix:
        include:
          # I dropped support for old versions intentionally - use original fdint if you need old Python
          - python-version: '2.7'
          - python-version: '3.6'
          - python-version: '3.7'
          - python-version: '3.8'
          - python-version: '3.9'
          - python-version: '3.10'
          - python-version: '3.11'
          - python-version: '3.12'
    container:
      image: "python:${{ matrix.python-version }}"

    steps:
    - uses: actions/checkout@v4
    - name: Prepare virtual env
      run: |
        pip install virtualenv
        python -m virtualenv venv
        venv/bin/pip install numpy Cython setuptools
        venv/bin/python setup.py install
    - name: Test with setup.py
      run: |
        cd ..
        "$OLDPWD/venv/bin/python" -m fdint.tests